### ISSUE TITLE
Cascadia Code == Ligature Issue

### ISSUE THREAD

**Issue by drcxd** [mickeynp/ligature.el#39]
As you can see, in the README of this repository, the double equal signs are not shown as ligatures.

I am using Emacs 28 on Windows (official released binary), it has Harfbuzz enabled but not Cario. Most ligatures in Cascaida Code could render properly, so I have not noticed that double equal signs are not shown as ligatures until I open the same file in Visual Studio. In Visual Studio, double equal signs are rendered properly as two parallel straight lines with no break in the middle. This is not the case in emacs using ligature.el.

Any idea how to fix this subtle problem?

**Comment by mickeynp** [comment]
Hi there.

Well, you know, I don't think it's a bug to be honest. Or rather, if it is, I'm not seeing it. Here's why:

https://github.com/microsoft/cascadia-code/blob/main/images/ligatures.png

Assuming it's up-to-date (it may not be) then `==` is indeed ligated correctly, as per their own instructions. I do know the Cascadia code font is regularly updated; it's definitely seen changes in the years I've been using it. So maybe that adds to the confusion.

The reason why it may look that way in VSCode is because -- I'm guessing -- the infinite arrow notation, which *does* work fine --- as does `===`.

So, hm... I don't know?

**Comment by drcxd** [comment]
Hi, you are correct. I misunderstood the situation. Actually, in Visual Studio, if I just type `==` then it is rendered like the ligature in the README. Then I type another `=`, so we have `===` it is rendered as the ligature for three consecutive equal signs. When I type the fourth `=` and even more `=`, all these equal signs become one big ligature (at least, it seems like this to me), two parallel straight lines without break in the middle. Is there any way we can configure ligature behaving like this in emacs?
"When there are four or more consecutive equals signs, just display two striangt lines"?
![image](https://user-images.githubusercontent.com/24535087/170613230-b9969cf2-2540-4f1a-9bb7-e32d880bdac3.png)
![image](https://user-images.githubusercontent.com/24535087/170613255-bef1aae9-23a5-4a7d-a947-3023fa6ae561.png)
![image](https://user-images.githubusercontent.com/24535087/170613275-44528c47-65ec-4350-83ae-8415f1fa1f55.png)
